name: Node.js CD

on:
  pull_request:
    types:
      - closed
    branches: ["main"]

jobs:
  deploy_image:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-20.04

    defaults:
      run:
        working-directory: ./app

    steps:
      - uses: actions/checkout@v4

      - name: Build docker image
        run: docker build . -t app-image

      - name: Run tests in container
        run: docker run app-image npm run test

      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Tag and push image
        run: |
          docker tag app-image ${{secrets.DOCKER_USERNAME}}/app-image:latest
          docker push ${{secrets.DOCKER_USERNAME}}/app-image:latest