name: Build and deploy docker image

on:
  pull_request:
    types:
      - closed
    branches: ["main"]

  workflow_dispatch:

jobs:
  build_and_deploy_docker_image:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-20.04

    defaults:
      run:
        working-directory: ./app

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create .env file
        run: echo ${{secrets.ENV_VARS}} > .env
        
      - name: Set env vars
        run: export $(cat .env | xargs)

      - name: Build docker image
        run: docker build . -t ${{secrets.DOCKER_IMAGE_NAME}}

      - name: Run tests in container
        run: docker run ${{secrets.DOCKER_IMAGE_NAME}} npm run test

      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Tag and push image
        run: |
          docker tag ${{secrets.DOCKER_IMAGE_NAME}} ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGE_NAME}}:latest
          docker push ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGE_NAME}}:latest